dist: trusty
sudo: required
language: node_js
node_js: "8"

jobs:
  include:
  - stage: deploy
    if: branch = master AND (NOT type IN (pull_request))
    provide: script
    skip_cleanup: true
    script:
    - git config --global user.email "releases@ladybug.tools"
    - git config --global user.name "ladybugbot"
    - npx semantic-release
